name: Run Pytest

on:
  push:
    branches:
      - main
      - developer
  pull_request:
    branches:
      - main
      - developer

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pytest .

    - name: Run pytest
      run: |
        pytest  tests
